name: Docker Image with Node
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18, 19]

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3
    - name: 'Login to Github container registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: namrataaws
        password: ${{ secrets.GHCR_PAT }}
    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.node_version }}/
        tags: ${{ vars.IMAGE_NAME }}:${{ matrix.node_version }}
        platforms: linux/amd64
        push: true